spellchecker: aspell
matrix:
- name: Text Files
  sources:
  - "**/*.txt"
  - "**/*.md"
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8

  ignores: 
  - Sauté
  - cannellini
  - flavour
  - flavours
  - mins
  - parmesan
  - passata
